### ISSUE TITLE
composer could not find package 

### ISSUE THREAD

**Issue by Blear** [sawirricardo/laravel-whatsapp#1]
`InvalidArgumentException]                                                                                                                                                                                                       Could not find a matching version of package sawirricardo/laravel-whatsapp. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev). `

I noticed that the package  is not yet available on packagist.org

**Comment by sawirricardo** [comment]
Hi @Blear , nice catch! I've put this in the composer https://packagist.org/packages/sawirricardo/laravel-whatsapp
